version: '3'
services:
    core:
      container_name: CORE-30001
      build: .
      env_file:
       - ./env/node-30001.env
      ports:
        - 30001:30001
      volumes:
        - .:/opt/app
      hostname: atajo.core.30001
      command: [ "node", "atajo.core.js"]
   
