version: '3'
services:
    core:
      container_name: CORE-30000
      build: .
      env_file:
       - ./env/node.env
      ports:
        - 30000:30000
      volumes:
        - .:/opt/app
      hostname: atajo.core.30000
      command: [ "node", "atajo.core.js"]
   
