version: '3'
services:
    core:
      build: .
      env_file:
       - ./env/node.env
      ports:
        - 30000:30000
        - 40000:40000
      volumes:
        - .:/opt/app
      hostname: atajo.core
      command: [ "node", "atajo.core.js"]
   
    